config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'udons/top' => 'udons#top'
 
  


  
  resources :users, only: [:index, :show, :new]
  resources :sindans
  resources :udons do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  
  end
  
  resources :sindans
  root 'udons#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :udon


end

app/models/like.rb
class Like < ApplicationRecord

    belongs_to :user
    belongs_to :udon

    validates_uniqueness_of :udon_id, scope: :user_id

end

app/models/sindan.rb
class Sindan < ApplicationRecord
end

app/models/udon.rb
class Udon < ApplicationRecord

    belongs_to :user

    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :udons, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
         
         has_many :likes, dependent: :destroy
         has_many :liked_udons, through: :likes, source: :udon
       
         has_many :comments, dependent: :destroy

         def already_liked?(udon)
          self.likes.exists?(udon_id: udon.id)
        end

         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 } #追記       
         mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


      protected
      def configure_permitted_parameters
    
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    
       devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
     end
 

    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
      udon = Udon.find(params[:udon_id])
      comment = udon.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(udon_id: params[:udon_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(udon_id: params[:udon_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController

  
    def index
        @sindan= Sindan.all
    end


    def new
        @sindan = Sindan.new
      end
    
      def show
        @sindan = Sindan.find(params[:id])
   end


      def create
        @sindan = Sindan.new(sindan_params)
        params[:sindan][:question] ? @sindan.question = params[:sindan][:question].join("") : false
        if @sindan.save
            flash[:notice] = "診断が完了しました"
            redirect_to sindan_path(@sindan.id)
        else
            redirect_to :action => "new"
        end
      end
    
      

      private
      def sindan_params
        params.require(:sindan).permit(:question, :user_id)
      end

end

app/controllers/udons_controller.rb
class UdonsController < ApplicationController


  
  before_action :authenticate_user!

    def index
        @udons = Udon.all

        if params[:search] == nil
          @udons= Udon.all
        elsif params[:search] == ''
          @udons= Udon.all
        else
          
          @udons = Udon.where("name LIKE ? ",'%' + params[:search] + '%')
        end

    end

    def new
        @udon = Udon.new
    end

    def create
        @udon = Udon.new(udon_params)
        @udon.user_id = current_user.id
      if @udon.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
       end
    end

    def show
      @udon = Udon.find(params[:id])
    
      @comments = @udon.comments
      @comment = Comment.new
    end


    def top
    end


    private
    def udon_params
      params.require(:udon).permit(:name, :place, :user_id, :image, :posted_date, :lat, :lng, :level, :overall, :shop)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id]) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/helpers/udons_helper.rb
module UdonsHelper

    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end

end

app/helpers/udonstars_helper.rb
module UdonstarsHelper

    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
         else
           return 0
        end

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udonsaito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css"> 
    


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sindans/new.html.erb
<h1>うどん診断</h1>


<%= form_for(@sindan, class: 'form-horizontal', role: 'form') do |f| %>
  <div class="container-sindan">
      <div class="row">
          <div class="col-2">
              <h3>Question1. 今の気分は…</h3>
         
              <h3><%= f.check_box :question, {multiple: true}, "1", nil %>ガッツリ食べたい</h3>
              <h3><%= f.check_box :question, {multiple: true}, "2", nil %>ガッツリ食べたい感じではない</h3>
          </div>

          <div class="col-2">
              <h3>Question2. 今飲みたい出汁は…</h3>
          
              <h3><%= f.check_box :question, {multiple: true}, "1", nil %>甘い感じがいい</h3>
              <h3><%= f.check_box :question, {multiple: true}, "2", nil %>甘くなくてよい</h3>
          </div>

          <div class="col-2">
              <h3>Question3. うどんのトッピングは…</h3>
          
              <h3><%= f.check_box :question, {multiple: true}, "1", nil %>揚げ物系がいい</h3>
              <h3><%= f.check_box :question, {multiple: true}, "2", nil %>変わり種が欲しい</h3>
          </div>

          <div class="col-2">
              <h3>Question4. サイドメニューは…</h3>
       
              <h3><%= f.check_box :question, {multiple: true}, "1", nil %>バラエティーに富んでいてほしい</h3>
              <h3><%= f.check_box :question, {multiple: true}, "2", nil %>サイドメニューは重視しない</h3>
          </div>

      </div>
  </div>
  <div class="sindanbotan">
      <%= f.submit "post" %>
  </div>
<% end %>


<%= form_for @sindan do |f| %>


  
<% end %>

<%= link_to "一覧に戻る", sindans_path %>

app/views/sindans/show.html.erb
<h1>診断結果</h1>

<div class="sindan">
  
  <p><%= @sindan.created_at %></p>
</div>


<div class="intoro">

<p>あなたにおすすめのうどんは…</p>
</div>
<div class="sindan-container">
<div class="sindan">
    <% if @sindan.question == "1111" %>
   
    <p>牧のうどんの</p>
    <p>肉ごぼう天うどん</p>
    <img src="images/画像のurl">
    <% elsif @sindan.question == "1112" %>

    <div class="oo">
      <p>牧のうどんの</p>
      <p>肉ごぼう天うどん</p>
      
    </div>

    <% elsif @sindan.question == "1121" %>
   
    <p>牧のうどんの</p>
    <p>唐揚げうどん</p>

    <% elsif @sindan.question == "1122" %>
    
    <p>牧のうどんの</p>
    <p>スペシャルうどん</p>

    <% elsif @sindan.question == "1211" %>
    
    <p>ウエストの</p>
    <p>かき揚げうどん</p>

    <% elsif @sindan.question == "1212" %>
    
    <p>牧のうどんの</p>
    <p>唐揚げうどん</p>

    <% elsif @sindan.question == "1221" %>
    
    <p>資さんうどんの</p>
    <p>鍋焼きうどん</p>

    <% elsif @sindan.question == "1222" %>
   
    <p>牧のうどんの</p>
    <p>スペシャルうどん</p>

    <% elsif @sindan.question == "2111" %>
    
    <p>資さんうどんの</p>
    <p>肉ごぼう天うどん</p>

    <% elsif @sindan.question == "2112" %>
    
    <p>ウエストの</p>
    <p>肉ごぼう天うどん</p>

    <% elsif @sindan.question == "2121" %>
   
    <p>資さんうどんの</p>
    <p>肉うどん</p>

    <% elsif @sindan.question == "2122" %>
    
    <p>ウエストの</p>
    <p>肉うどん</p>

    <% elsif @sindan.question == "2211" %>
    
    <p>資さんうどんの</p>
    <p>かき揚げうどん</p>

    <% elsif @sindan.question == "2212" %>
    
    <p>ウエストの</p>
    <p>ごぼう天うどん</p>

    <% elsif @sindan.question == "2221" %>
    
    <p>牧のうどんの</p>
    <p>スペシャルうどん</p>

    <% elsif @sindan.question == "2222" %>
   
    <p>牧のうどんの</p>
    <p>スペシャルうどん</p>

    <% end %>

</div>


<div class="ss">
<%= link_to "Sindan一覧に戻る", sindans_path %>
</div>

app/views/udons/index.html.erb
<h1>udonsaito</h1>

<div class="inu1">
<h3>投稿を検索</h3>
</div>

 <%= form_tag({controller:"udons",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<div class="inu">
 <h3>一覧ページ</h3>
</div>
<%= link_to '新規投稿へ', new_udon_path %> 

<body>
 <div class="udons-container">
  <% @udons.each do |t| %>
        <div class="udon">
        <div class="user">
          <%= image_tag t.user.image_url, :style => "border-radius:50%", size: "40x40" if t.user.image? %>
        </div>
       <div class="username">
           <% if user_signed_in? %>
               <%= link_to t.user.name, user_path(t.user.id) %>  
           <% else %>
               <%= link_to t.user.name, new_user_session_path %>
           <% end %>
       </div>
            <%= image_tag t.image_url, size: "250x200" if t.image? %>
            <%= t.shop %>
            <%= t.place %>
            <%= t.posted_date %>
            <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <% if user_signed_in? %>

                  <% if current_user.already_liked?(t) %>
                          <%= button_to udon_like_path(id: t.id, udon_id: t.id), method: :delete do %>
                            <i class="fa-sharp fa-solid fa-heart"></i><%= t.likes.count %>
                          <% end %>
                  <% else %>
                          <%= button_to udon_likes_path(id: t.id, udon_id: t.id), method: :post do %>
                            <i class="fa-sharp fa-solid fa-heart"></i><%= t.likes.count %>
                          <% end %>
                   <% end %>
          <% else %>
          <i class="fa-sharp fa-solid fa-heart"></i><%= t.likes.count %>
          <% end %>
    

      <div>
          <h2>総合評価：
              <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
              </span>
            </h2>
        </div>

        
       <div>
            <h2>うどんレベル：
                <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
                </span>
            </h2>
      </div>
      <%= link_to "詳細へ", udon_path(t.id) %>
            
      </div>

   
    <div class="neko">
      <%= link_to "マイページへ", user_path(current_user.id) %>
    </div>

    <div class="neko1">
      <%= link_to "新規投稿へ", new_udon_path %>
    </div> 
    

    <div class="log">
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    </div> 

      <% end %>
  </div>
</body>

app/views/udons/new.html.erb
<h1>UdonPost</h1>

<h2>新規udon</h2>

<%= form_for @udon do |f| %>
  <div class="abcd">
    <div class="udonstar_form">
    <h3>うどん投稿フォーム</h3>
    <%= f.text_field :name , placeholder: 'うどん名を入力', class:'name_field'%>
    
  
    <h4>総合評価</h4>
     <div class="post_form">
      <%= f.radio_button :overall, 5 ,id: 'star1'%>
      <label for="star1"><span class="text">最高</span>★</label>
  
      <%= f.radio_button :overall, 4 ,id: 'star2'%>
      <label for="star2"><span class="text">良い</span>★</label>
  
      <%= f.radio_button :overall, 3 ,id: 'star3'%>
      <label for="star3"><span class="text">普通</span>★</label>
  
      <%= f.radio_button :overall, 2 ,id: 'star4'%>
      <label for="star4"><span class="text">悪い</span>★</label>
  
      <%= f.radio_button :overall, 1 ,id: 'star5'%>
      <label for="star5"><span class="text">最悪</span>★</label>
   </div>
  
  <h4>うどんレベル</h4>
    <div class="post_form">
      <%= f.radio_button :level,  5 ,id: 'star6'%>
      <label for="star6"><span class="text">おいしい</span>★</label>
  
      <%= f.radio_button :level,  4 ,id: 'star7'%>
      <label for="star7"><span class="text">まあまあおいしい</span>★</label>
  
      <%= f.radio_button :level, 3 ,id: 'star8'%>
      <label for="star8"><span class="text">普通</span>★</label>
  
      <%= f.radio_button :level , 2 ,id: 'star9'%>
      <label for="star9"><span class="text">あまりおいしくない</span>★</label>
  
      <%= f.radio_button :level , 1 ,id: 'star10'%>
      <label for="star10"><span class="text">おいしくない</span>★</label>
   </div>
  
  
    </div>
    

  


<div class="udonstar_form">
  <div class="field1">
    <%= f.label :shop %>
    <%= f.text_field :shop, :size => 30 %>
  </div>


  <div class="field1">
    <%= f.label :place %>
    <%= f.text_field :place, :size => 30 %>
  </div>

    <div class="field1">
       <%= f.label :image %>
        <%= f.file_field :image %>
    </div>
 </div>
 </div>


  <%= f.submit "投稿する" %>
<% end %>


<%= link_to "一覧に戻る", udons_path %>

app/views/udons/show.html.erb
<h1>Udon</h1>
<h3>Udon詳細</h3>
<div class="udon">
  
  <p><%= @udon.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@udon) %>
        <%= button_to udon_like_path(@udon), method: :delete do %>
          <i class="fas fa-heart"></i><%= @udon.likes.count %>
        <% end %>
      <% else %>
        <%= button_to udon_likes_path(@udon), method: :post do %>
          <i class="far fa-heart"></i><%= @udon.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @udon.likes.count %>
    <% end %>
  
</div>

<h2>いいねしたユーザー</h2>
<% @udon.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@udon, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Udon一覧に戻る", udons_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<h2>ユーザーの投稿一覧</h2>
<% @user.udons.each do |t| %>
  <div class="udon">
        <div class="user">
          <%= image_tag t.user.image_url, :style => "border-radius:50%", size: "40x40" if t.user.image? %>
        </div>
       <div class="username">
           <% if user_signed_in? %>
               <%= link_to t.user.name, user_path(t.user.id) %>  
           <% else %>
               <%= link_to t.user.name, new_user_session_path %>
           <% end %>
       </div>
            <%= image_tag t.image_url, size: "250x200" if t.image? %>
          
            <%= t.place %>
            <%= t.posted_date %>
           
            <% if user_signed_in? %>

                  <% if current_user.already_liked?(t) %>
                          <%= button_to udon_like_path(id: t.id, udon_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                          <% end %>
                  <% else %>
                          <%= button_to udon_likes_path(id: t.id, udon_id: t.id), method: :post do %>
                              <i class="far fa-heart"></i><%= t.likes.count %>
                          <% end %>
                   <% end %>
          <% else %>
              <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
    
      <div>
          <h2>総合評価：
              <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
              </span>
            </h2>
        </div>

       <div>
            <h2>うどんレベル：
                <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
                </span>
            </h2>
      </div>
      <%= link_to "詳細へ", udon_path(t.id) %>
            
      </div>

<% end %>




<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_udons.each do |t| %>
  <div class="udon">
        <div class="user">
          <%= image_tag t.user.image_url, :style => "border-radius:50%", size: "40x40" if t.user.image? %>
        </div>
       <div class="username">
           <% if user_signed_in? %>
               <%= link_to t.user.name, user_path(t.user.id) %>  
           <% else %>
               <%= link_to t.user.name, new_user_session_path %>
           <% end %>
       </div>
            <%= image_tag t.image_url, size: "250x200" if t.image? %>
          
            <%= t.place %>
            <%= t.posted_date %>
            <%= link_to "詳細へ", udon_path(t.id) %>
            <% if user_signed_in? %>

                  <% if current_user.already_liked?(t) %>
                          <%= link_to udon_like_path(id: t.id, udon_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                          <% end %>
                  <% else %>
                          <%= link_to udon_likes_path(id: t.id, udon_id: t.id), method: :post do %>
                              <i class="far fa-heart"></i><%= t.likes.count %>
                          <% end %>
                   <% end %>
          <% else %>
              <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
    
      <div>
          <h2>総合評価：
              <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
              </span>
            </h2>
        </div>

       <div>
            <h2>うどんレベル：
                <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
                </span>
            </h2>
      </div>
      <%= link_to "詳細へ", udon_path(t.id) %>
            
    </div>

      


<% end %>
<!-- ここまで-->

<%= link_to "Udon一覧に戻る", udons_path %>